from static_dependency_injector.containers._container_config_dict import ContainerConfigDict
from static_dependency_injector.containers._static_declarative_container import StaticDeclarativeContainer

__all__ = ("ContainerConfigDict", "StaticDeclarativeContainer")
